/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    pages: Page;
    posts: Post;
    'navigation-menus': NavigationMenu;
    headers: Header;
    footers: Footer;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'navigation-menus': NavigationMenusSelect<false> | NavigationMenusSelect<true>;
    headers: HeadersSelect<false> | HeadersSelect<true>;
    footers: FootersSelect<false> | FootersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User role determines access level and permissions
   */
  role: 'superadmin' | 'tenantAdmin' | 'editor';
  /**
   * Required for Tenant Admin and Editor roles
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  projectName: string;
  /**
   * Unique slug-like identifier (e.g., "ftiaxesite", "kallitechnia")
   */
  code: string;
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'inactive';
  /**
   * Internal notes about this tenant
   */
  notes?: string | null;
  /**
   * Primary brand color (hex code)
   */
  primaryColor?: string | null;
  /**
   * Secondary brand color (hex code)
   */
  secondaryColor?: string | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * The tenant this media belongs to
   */
  tenant?: (number | null) | Tenant;
  /**
   * Alternative text for accessibility and SEO
   */
  alt: string;
  createdAt: string;
  updatedAt: string;
  prefix?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The tenant this page belongs to
   */
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Optional headline (often used for homepage hero sections). If empty, page title will be used.
   */
  headline?: string | null;
  /**
   * Auto-generated from title. URL-friendly identifier for this page.
   */
  slug: string;
  blocks?:
    | (
        | {
            /**
             * Internal label to identify this section (e.g., "Hero", "Features")
             */
            blockLabel?: string | null;
            title?: string | null;
            subtitle?: string | null;
            backgroundImage?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Internal label to identify this section (e.g., "About", "Features", "Content")
             */
            blockLabel?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Internal label to identify this section (e.g., "Gallery", "Images", "Photo Gallery")
             */
            blockLabel?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            /**
             * Internal label to identify this section (e.g., "About", "Welcome")
             */
            blockLabel?: string | null;
            title?: string | null;
            subtitle?: string | null;
            image?: (number | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            /**
             * Internal label to identify this section (e.g., "Programs", "Services", "Features")
             */
            blockLabel?: string | null;
            title?: string | null;
            subtitle?: string | null;
            cards?:
              | {
                  image?: (number | null) | Media;
                  title?: string | null;
                  description?: string | null;
                  buttonLabel?: string | null;
                  buttonUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            /**
             * Internal label to identify this section (e.g., "Sponsors", "Partners")
             */
            blockLabel?: string | null;
            title?: string | null;
            subtitle?: string | null;
            sponsors?:
              | {
                  image: number | Media;
                  title?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sponsors';
          }
        | {
            /**
             * Internal label to identify this section (e.g., "Programs", "Τμήματα")
             */
            blockLabel?: string | null;
            title?: string | null;
            subtitle?: string | null;
            programs?:
              | {
                  title?: string | null;
                  image?: (number | null) | Media;
                  description?: string | null;
                  additionalInfo?: string | null;
                  imagePosition?: ('left' | 'right') | null;
                  schedule?:
                    | {
                        day?: string | null;
                        time?: string | null;
                        level?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  coach?: {
                    name?: string | null;
                    photo?: (number | null) | Media;
                    studies?: string | null;
                    bio?: string | null;
                    imagePosition?: ('left' | 'right') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programs';
          }
      )[]
    | null;
  /**
   * SEO title (max 60 characters). If empty, page title will be used.
   */
  seoTitle?: string | null;
  /**
   * SEO meta description (max 160 characters)
   */
  seoDescription?: string | null;
  featuredImage?: (number | null) | Media;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The tenant this post belongs to
   */
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Auto-generated from title. URL-friendly identifier for this post.
   */
  slug: string;
  /**
   * Short summary for listings
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * SEO title (max 60 characters). If empty, post title will be used.
   */
  seoTitle?: string | null;
  /**
   * SEO meta description (max 160 characters)
   */
  seoDescription?: string | null;
  featuredImage?: (number | null) | Media;
  author?: (number | null) | User;
  publishedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus".
 */
export interface NavigationMenu {
  id: number;
  /**
   * The tenant this navigation menu belongs to
   */
  tenant?: (number | null) | Tenant;
  /**
   * e.g., "Main Menu", "Footer Menu"
   */
  title: string;
  items?:
    | {
        label: string;
        type: 'internal' | 'external';
        /**
         * Select a page for internal links
         */
        page?: (number | null) | Page;
        /**
         * External URL (e.g., https://example.com)
         */
        url?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headers".
 */
export interface Header {
  id: number;
  /**
   * The tenant this header belongs to
   */
  tenant?: (number | null) | Tenant;
  /**
   * e.g., "Default Header"
   */
  label: string;
  logo?: (number | null) | Media;
  navigationMenu?: (number | null) | NavigationMenu;
  enableTopBar?: boolean | null;
  /**
   * Text to display in the top bar
   */
  topBarText?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers".
 */
export interface Footer {
  id: number;
  /**
   * The tenant this footer belongs to
   */
  tenant?: (number | null) | Tenant;
  /**
   * e.g., "Default Footer"
   */
  label: string;
  footerMenus?:
    | {
        title: string;
        menu?: (number | null) | NavigationMenu;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok' | 'other';
        /**
         * Full URL to the social media profile
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO title (max 60 characters)
   */
  seoTitle?: string | null;
  /**
   * SEO meta description (max 160 characters)
   */
  seoDescription?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'navigation-menus';
        value: number | NavigationMenu;
      } | null)
    | ({
        relationTo: 'headers';
        value: number | Header;
      } | null)
    | ({
        relationTo: 'footers';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  projectName?: T;
  code?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  status?: T;
  notes?: T;
  primaryColor?: T;
  secondaryColor?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  headline?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              blockLabel?: T;
              title?: T;
              subtitle?: T;
              backgroundImage?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              blockLabel?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              blockLabel?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              blockLabel?: T;
              title?: T;
              subtitle?: T;
              image?: T;
              imagePosition?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              blockLabel?: T;
              title?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    buttonLabel?: T;
                    buttonUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        sponsors?:
          | T
          | {
              blockLabel?: T;
              title?: T;
              subtitle?: T;
              sponsors?:
                | T
                | {
                    image?: T;
                    title?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        programs?:
          | T
          | {
              blockLabel?: T;
              title?: T;
              subtitle?: T;
              programs?:
                | T
                | {
                    title?: T;
                    image?: T;
                    description?: T;
                    additionalInfo?: T;
                    imagePosition?: T;
                    schedule?:
                      | T
                      | {
                          day?: T;
                          time?: T;
                          level?: T;
                          id?: T;
                        };
                    coach?:
                      | T
                      | {
                          name?: T;
                          photo?: T;
                          studies?: T;
                          bio?: T;
                          imagePosition?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  featuredImage?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  seoTitle?: T;
  seoDescription?: T;
  featuredImage?: T;
  author?: T;
  publishedAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus_select".
 */
export interface NavigationMenusSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  items?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headers_select".
 */
export interface HeadersSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  logo?: T;
  navigationMenu?: T;
  enableTopBar?: T;
  topBarText?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers_select".
 */
export interface FootersSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  footerMenus?:
    | T
    | {
        title?: T;
        menu?: T;
        id?: T;
      };
  copyrightText?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  createdAt?: T;
  updatedAt?: T;
  prefix?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}