/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  text,
  jsonb,
  boolean,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['superadmin', 'tenantAdmin', 'editor'])
export const enum_tenants_status = pgEnum('enum_tenants_status', ['active', 'inactive'])
export const enum_navigation_menus_items_type = pgEnum('enum_navigation_menus_items_type', [
  'internal',
  'external',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    role: enum_users_role('role').notNull().default('editor'),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_tenant_idx').on(columns.tenant),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const tenants_domains = pgTable(
  'tenants_domains',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    domain: varchar('domain').notNull(),
  },
  (columns) => [
    index('tenants_domains_order_idx').on(columns._order),
    index('tenants_domains_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_domains_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants = pgTable(
  'tenants',
  {
    id: serial('id').primaryKey(),
    projectName: varchar('project_name').notNull(),
    code: varchar('code').notNull(),
    status: enum_tenants_status('status').notNull().default('active'),
    notes: varchar('notes'),
    primaryColor: varchar('primary_color'),
    secondaryColor: varchar('secondary_color'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('tenants_code_idx').on(columns.code),
    index('tenants_logo_idx').on(columns.logo),
    index('tenants_updated_at_idx').on(columns.updatedAt),
    index('tenants_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_blocks_hero = pgTable(
  'pages_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    subtitle: varchar('subtitle'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    ctaLabel: varchar('cta_label'),
    ctaUrl: varchar('cta_url'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_hero_order_idx').on(columns._order),
    index('pages_blocks_hero_parent_id_idx').on(columns._parentID),
    index('pages_blocks_hero_path_idx').on(columns._path),
    index('pages_blocks_hero_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_rich_text = pgTable(
  'pages_blocks_rich_text',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    content: jsonb('content'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_rich_text_order_idx').on(columns._order),
    index('pages_blocks_rich_text_parent_id_idx').on(columns._parentID),
    index('pages_blocks_rich_text_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_rich_text_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_image_gallery_images = pgTable(
  'pages_blocks_image_gallery_images',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => [
    index('pages_blocks_image_gallery_images_order_idx').on(columns._order),
    index('pages_blocks_image_gallery_images_parent_id_idx').on(columns._parentID),
    index('pages_blocks_image_gallery_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_image_gallery.id],
      name: 'pages_blocks_image_gallery_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_image_gallery = pgTable(
  'pages_blocks_image_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_image_gallery_order_idx').on(columns._order),
    index('pages_blocks_image_gallery_parent_id_idx').on(columns._parentID),
    index('pages_blocks_image_gallery_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_image_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    seoTitle: varchar('seo_title'),
    seoDescription: varchar('seo_description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('pages_tenant_idx').on(columns.tenant),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ],
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    excerpt: varchar('excerpt'),
    content: jsonb('content'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('posts_tenant_idx').on(columns.tenant),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
  ],
)

export const navigation_menus_items = pgTable(
  'navigation_menus_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    type: enum_navigation_menus_items_type('type').notNull().default('internal'),
    page: integer('page_id').references(() => pages.id, {
      onDelete: 'set null',
    }),
    url: varchar('url'),
    openInNewTab: boolean('open_in_new_tab').default(false),
  },
  (columns) => [
    index('navigation_menus_items_order_idx').on(columns._order),
    index('navigation_menus_items_parent_id_idx').on(columns._parentID),
    index('navigation_menus_items_page_idx').on(columns.page),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [navigation_menus.id],
      name: 'navigation_menus_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const navigation_menus = pgTable(
  'navigation_menus',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    title: varchar('title').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('navigation_menus_tenant_idx').on(columns.tenant),
    index('navigation_menus_updated_at_idx').on(columns.updatedAt),
    index('navigation_menus_created_at_idx').on(columns.createdAt),
  ],
)

export const headers = pgTable(
  'headers',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    label: varchar('label').notNull().default('Default Header'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    navigation: integer('navigation_id').references(() => navigation_menus.id, {
      onDelete: 'set null',
    }),
    showTopBar: boolean('show_top_bar').default(false),
    topBarText: varchar('top_bar_text'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('headers_tenant_idx').on(columns.tenant),
    index('headers_logo_idx').on(columns.logo),
    index('headers_navigation_idx').on(columns.navigation),
    index('headers_updated_at_idx').on(columns.updatedAt),
    index('headers_created_at_idx').on(columns.createdAt),
  ],
)

export const footers_social_links = pgTable(
  'footers_social_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    url: varchar('url').notNull(),
  },
  (columns) => [
    index('footers_social_links_order_idx').on(columns._order),
    index('footers_social_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footers.id],
      name: 'footers_social_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const footers = pgTable(
  'footers',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    label: varchar('label').notNull().default('Default Footer'),
    navigation: integer('navigation_id').references(() => navigation_menus.id, {
      onDelete: 'set null',
    }),
    copyrightText: varchar('copyright_text'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('footers_tenant_idx').on(columns.tenant),
    index('footers_navigation_idx').on(columns.navigation),
    index('footers_updated_at_idx').on(columns.updatedAt),
    index('footers_created_at_idx').on(columns.createdAt),
  ],
)

export const homepages_blocks_hero = pgTable(
  'homepages_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    subtitle: varchar('subtitle'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    ctaLabel: varchar('cta_label'),
    ctaUrl: varchar('cta_url'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('homepages_blocks_hero_order_idx').on(columns._order),
    index('homepages_blocks_hero_parent_id_idx').on(columns._parentID),
    index('homepages_blocks_hero_path_idx').on(columns._path),
    index('homepages_blocks_hero_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepages.id],
      name: 'homepages_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepages_blocks_rich_text = pgTable(
  'homepages_blocks_rich_text',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    content: jsonb('content'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('homepages_blocks_rich_text_order_idx').on(columns._order),
    index('homepages_blocks_rich_text_parent_id_idx').on(columns._parentID),
    index('homepages_blocks_rich_text_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepages.id],
      name: 'homepages_blocks_rich_text_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepages_blocks_image_gallery_images = pgTable(
  'homepages_blocks_image_gallery_images',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => [
    index('homepages_blocks_image_gallery_images_order_idx').on(columns._order),
    index('homepages_blocks_image_gallery_images_parent_id_idx').on(columns._parentID),
    index('homepages_blocks_image_gallery_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepages_blocks_image_gallery.id],
      name: 'homepages_blocks_image_gallery_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepages_blocks_image_gallery = pgTable(
  'homepages_blocks_image_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('homepages_blocks_image_gallery_order_idx').on(columns._order),
    index('homepages_blocks_image_gallery_parent_id_idx').on(columns._parentID),
    index('homepages_blocks_image_gallery_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepages.id],
      name: 'homepages_blocks_image_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepages = pgTable(
  'homepages',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    label: varchar('label').notNull().default('Default Homepage'),
    slug: varchar('slug').notNull().default('home'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('homepages_tenant_idx').on(columns.tenant),
    index('homepages_updated_at_idx').on(columns.updatedAt),
    index('homepages_created_at_idx').on(columns.createdAt),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    prefix: varchar('prefix').default('media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_tenant_idx').on(columns.tenant),
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    tenantsID: integer('tenants_id'),
    pagesID: integer('pages_id'),
    postsID: integer('posts_id'),
    'navigation-menusID': integer('navigation_menus_id'),
    headersID: integer('headers_id'),
    footersID: integer('footers_id'),
    homepagesID: integer('homepages_id'),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_tenants_id_idx').on(columns.tenantsID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_navigation_menus_id_idx').on(
      columns['navigation-menusID'],
    ),
    index('payload_locked_documents_rels_headers_id_idx').on(columns.headersID),
    index('payload_locked_documents_rels_footers_id_idx').on(columns.footersID),
    index('payload_locked_documents_rels_homepages_id_idx').on(columns.homepagesID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tenantsID']],
      foreignColumns: [tenants.id],
      name: 'payload_locked_documents_rels_tenants_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['navigation-menusID']],
      foreignColumns: [navigation_menus.id],
      name: 'payload_locked_documents_rels_navigation_menus_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['headersID']],
      foreignColumns: [headers.id],
      name: 'payload_locked_documents_rels_headers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['footersID']],
      foreignColumns: [footers.id],
      name: 'payload_locked_documents_rels_footers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['homepagesID']],
      foreignColumns: [homepages.id],
      name: 'payload_locked_documents_rels_homepages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [users.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_tenants_domains = relations(tenants_domains, ({ one }) => ({
  _parentID: one(tenants, {
    fields: [tenants_domains._parentID],
    references: [tenants.id],
    relationName: 'domains',
  }),
}))
export const relations_tenants = relations(tenants, ({ one, many }) => ({
  domains: many(tenants_domains, {
    relationName: 'domains',
  }),
  logo: one(media, {
    fields: [tenants.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations_pages_blocks_hero = relations(pages_blocks_hero, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_hero._parentID],
    references: [pages.id],
    relationName: '_blocks_hero',
  }),
  backgroundImage: one(media, {
    fields: [pages_blocks_hero.backgroundImage],
    references: [media.id],
    relationName: 'backgroundImage',
  }),
}))
export const relations_pages_blocks_rich_text = relations(pages_blocks_rich_text, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_rich_text._parentID],
    references: [pages.id],
    relationName: '_blocks_richText',
  }),
}))
export const relations_pages_blocks_image_gallery_images = relations(
  pages_blocks_image_gallery_images,
  ({ one }) => ({
    _parentID: one(pages_blocks_image_gallery, {
      fields: [pages_blocks_image_gallery_images._parentID],
      references: [pages_blocks_image_gallery.id],
      relationName: 'images',
    }),
    image: one(media, {
      fields: [pages_blocks_image_gallery_images.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_pages_blocks_image_gallery = relations(
  pages_blocks_image_gallery,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_image_gallery._parentID],
      references: [pages.id],
      relationName: '_blocks_imageGallery',
    }),
    images: many(pages_blocks_image_gallery_images, {
      relationName: 'images',
    }),
  }),
)
export const relations_pages = relations(pages, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [pages.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  _blocks_hero: many(pages_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  _blocks_richText: many(pages_blocks_rich_text, {
    relationName: '_blocks_richText',
  }),
  _blocks_imageGallery: many(pages_blocks_image_gallery, {
    relationName: '_blocks_imageGallery',
  }),
}))
export const relations_posts = relations(posts, ({ one }) => ({
  tenant: one(tenants, {
    fields: [posts.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
}))
export const relations_navigation_menus_items = relations(navigation_menus_items, ({ one }) => ({
  _parentID: one(navigation_menus, {
    fields: [navigation_menus_items._parentID],
    references: [navigation_menus.id],
    relationName: 'items',
  }),
  page: one(pages, {
    fields: [navigation_menus_items.page],
    references: [pages.id],
    relationName: 'page',
  }),
}))
export const relations_navigation_menus = relations(navigation_menus, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [navigation_menus.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  items: many(navigation_menus_items, {
    relationName: 'items',
  }),
}))
export const relations_headers = relations(headers, ({ one }) => ({
  tenant: one(tenants, {
    fields: [headers.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  logo: one(media, {
    fields: [headers.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  navigation: one(navigation_menus, {
    fields: [headers.navigation],
    references: [navigation_menus.id],
    relationName: 'navigation',
  }),
}))
export const relations_footers_social_links = relations(footers_social_links, ({ one }) => ({
  _parentID: one(footers, {
    fields: [footers_social_links._parentID],
    references: [footers.id],
    relationName: 'socialLinks',
  }),
}))
export const relations_footers = relations(footers, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [footers.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  navigation: one(navigation_menus, {
    fields: [footers.navigation],
    references: [navigation_menus.id],
    relationName: 'navigation',
  }),
  socialLinks: many(footers_social_links, {
    relationName: 'socialLinks',
  }),
}))
export const relations_homepages_blocks_hero = relations(homepages_blocks_hero, ({ one }) => ({
  _parentID: one(homepages, {
    fields: [homepages_blocks_hero._parentID],
    references: [homepages.id],
    relationName: '_blocks_hero',
  }),
  backgroundImage: one(media, {
    fields: [homepages_blocks_hero.backgroundImage],
    references: [media.id],
    relationName: 'backgroundImage',
  }),
}))
export const relations_homepages_blocks_rich_text = relations(
  homepages_blocks_rich_text,
  ({ one }) => ({
    _parentID: one(homepages, {
      fields: [homepages_blocks_rich_text._parentID],
      references: [homepages.id],
      relationName: '_blocks_richText',
    }),
  }),
)
export const relations_homepages_blocks_image_gallery_images = relations(
  homepages_blocks_image_gallery_images,
  ({ one }) => ({
    _parentID: one(homepages_blocks_image_gallery, {
      fields: [homepages_blocks_image_gallery_images._parentID],
      references: [homepages_blocks_image_gallery.id],
      relationName: 'images',
    }),
    image: one(media, {
      fields: [homepages_blocks_image_gallery_images.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_homepages_blocks_image_gallery = relations(
  homepages_blocks_image_gallery,
  ({ one, many }) => ({
    _parentID: one(homepages, {
      fields: [homepages_blocks_image_gallery._parentID],
      references: [homepages.id],
      relationName: '_blocks_imageGallery',
    }),
    images: many(homepages_blocks_image_gallery_images, {
      relationName: 'images',
    }),
  }),
)
export const relations_homepages = relations(homepages, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [homepages.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  _blocks_hero: many(homepages_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  _blocks_richText: many(homepages_blocks_rich_text, {
    relationName: '_blocks_richText',
  }),
  _blocks_imageGallery: many(homepages_blocks_image_gallery, {
    relationName: '_blocks_imageGallery',
  }),
}))
export const relations_media = relations(media, ({ one }) => ({
  tenant: one(tenants, {
    fields: [media.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    tenantsID: one(tenants, {
      fields: [payload_locked_documents_rels.tenantsID],
      references: [tenants.id],
      relationName: 'tenants',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    'navigation-menusID': one(navigation_menus, {
      fields: [payload_locked_documents_rels['navigation-menusID']],
      references: [navigation_menus.id],
      relationName: 'navigation-menus',
    }),
    headersID: one(headers, {
      fields: [payload_locked_documents_rels.headersID],
      references: [headers.id],
      relationName: 'headers',
    }),
    footersID: one(footers, {
      fields: [payload_locked_documents_rels.footersID],
      references: [footers.id],
      relationName: 'footers',
    }),
    homepagesID: one(homepages, {
      fields: [payload_locked_documents_rels.homepagesID],
      references: [homepages.id],
      relationName: 'homepages',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_tenants_status: typeof enum_tenants_status
  enum_navigation_menus_items_type: typeof enum_navigation_menus_items_type
  users_sessions: typeof users_sessions
  users: typeof users
  tenants_domains: typeof tenants_domains
  tenants: typeof tenants
  pages_blocks_hero: typeof pages_blocks_hero
  pages_blocks_rich_text: typeof pages_blocks_rich_text
  pages_blocks_image_gallery_images: typeof pages_blocks_image_gallery_images
  pages_blocks_image_gallery: typeof pages_blocks_image_gallery
  pages: typeof pages
  posts: typeof posts
  navigation_menus_items: typeof navigation_menus_items
  navigation_menus: typeof navigation_menus
  headers: typeof headers
  footers_social_links: typeof footers_social_links
  footers: typeof footers
  homepages_blocks_hero: typeof homepages_blocks_hero
  homepages_blocks_rich_text: typeof homepages_blocks_rich_text
  homepages_blocks_image_gallery_images: typeof homepages_blocks_image_gallery_images
  homepages_blocks_image_gallery: typeof homepages_blocks_image_gallery
  homepages: typeof homepages
  media: typeof media
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_tenants_domains: typeof relations_tenants_domains
  relations_tenants: typeof relations_tenants
  relations_pages_blocks_hero: typeof relations_pages_blocks_hero
  relations_pages_blocks_rich_text: typeof relations_pages_blocks_rich_text
  relations_pages_blocks_image_gallery_images: typeof relations_pages_blocks_image_gallery_images
  relations_pages_blocks_image_gallery: typeof relations_pages_blocks_image_gallery
  relations_pages: typeof relations_pages
  relations_posts: typeof relations_posts
  relations_navigation_menus_items: typeof relations_navigation_menus_items
  relations_navigation_menus: typeof relations_navigation_menus
  relations_headers: typeof relations_headers
  relations_footers_social_links: typeof relations_footers_social_links
  relations_footers: typeof relations_footers
  relations_homepages_blocks_hero: typeof relations_homepages_blocks_hero
  relations_homepages_blocks_rich_text: typeof relations_homepages_blocks_rich_text
  relations_homepages_blocks_image_gallery_images: typeof relations_homepages_blocks_image_gallery_images
  relations_homepages_blocks_image_gallery: typeof relations_homepages_blocks_image_gallery
  relations_homepages: typeof relations_homepages
  relations_media: typeof relations_media
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
